# Generated by Django 4.2 on 2023-05-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_ordered_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordered_Products',
        ),
    ]
