# Generated by Django 4.2 on 2023-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_remove_itemsmodel_customer_itemsmodel_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsmodel',
            name='customers',
        ),
        migrations.AddField(
            model_name='itemsmodel',
            name='customer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
