# Generated by Django 4.2 on 2023-05-18 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0006_remove_itemsmodel_customers_itemsmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsmodel',
            name='customer',
        ),
        migrations.AddField(
            model_name='itemsmodel',
            name='customer',
            field=models.ManyToManyField(blank=True, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
