# Generated by Django 4.2 on 2023-05-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_debt_supplier_alter_debt_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='seen',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
