# Generated by Django 4.2 on 2023-05-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_debt_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debt',
            field=models.IntegerField(),
        ),
    ]
